include_recipe 'apt'

# Development
package 'ack-grep'
package 'awesome'
package 'bison'
package 'build-essential'
package 'clang'
package 'clang-format-3.6'
package 'cmake'
package 'curl'
package 'exuberant-ctags'
package 'flex'
package 'gdb'
package 'graphviz'
package 'icedtea-netx'
package 'icedtea-plugin'
package 'keepass2'
package 'npm'
package 'pandoc'
package 'pkg-config'
package 'shellcheck'
package 'subversion'
package 'texlive-latex-base'
package 'tmux'
package 'vim-gtk'
package 'xclip'
package 'xsel'
package 'zsh'


# Browsers
package 'chromium-browser'
package 'flashplugin-installer'

# Networking
package 'curl'
package 'filezilla'
package 'nmap'
package 'vinagre'
package 'wireshark'

# Media
package 'calibre'
package 'gimp'
package 'imagemagick'
package 'libav-tools'
package 'libavcodec-extra'
package 'mupdf'
package 'totem'
package 'vlc'
package 'xbmc'

# Other
package 'deluge'
package 'htop'

# Languages
package 'cabal-install'
package 'ghc'
package 'ghc-mod'
package 'golang'
package 'mit-scheme'
package 'octave'
package 'python'
package 'ipython'
package 'ipython-qtconsole'
package 'python-dev'
package 'python-pip'
package 'python-sklearn'
package 'python-software-properties'
