#!/usr/bin/env bash

trayer \
  --edge top \
  --align right \
  --SetDockType true \
  --SetPartialStrut true \
  --expand true \
  --width 10 \
  --transparent true \
  --tint 0x191970 \
  --height 15 &

xmodmap ~/.xmodmap
