#!/usr/bin/env bash

has_uncommitted_changes() {
  diff=$(git diff-index HEAD)
  if [ -n "$diff" ]; then
    return 0
  fi
  return 1
}

is_on_master() {
  branch=$(git symbolic-ref HEAD 2>/dev/null | cut -d'/' -f3)
  if [ "$branch" == "master" ]; then
    return 0
  else
    return 1
  fi
}

check_submodules_and_commit_on_update() {
  git submodule update --remote --init
  if has_uncommitted_changes "$1"; then
    git add -u
    git commit -m "updating submodules [autogenerated]"
  fi
}

update() {
  f() {
    echo "Synchronizing $1"
    cd "$1" || exit 1
    if is_on_master && ! has_uncommitted_changes "$1"; then
      git pull
      check_submodules_and_commit_on_update "$1"
      git push
    else
      echo "Skipping $1 -- not in a valid state to sync"
    fi
  }
  if [ -d "$1" ]; then
    f "$1"
  else
    echo "Skipping $1 -- Not deployed on this machine."
  fi
}

echo "Updating repos"

update ~/.dotfiles
update ~/.dotfiles_local
update ~/notes

wait
echo "Finished updating repos"
