#!/bin/sh
lint()
{
    fileregex="$1"
    binary="$2"

    files=$(git diff --name-only --cached -- "$fileregex")
    if [ -z "$files" ]; then
        return
    fi

    lint=$(echo "$files" | xargs "$binary")
    if [ "$?" -ne "0" ]; then
        echo "$binary linting errors:"
        echo "$lint"
        exit 1
    fi
}

lint "*.hs" "hlint"
lint "*.py" "pyflakes"
lint "*.sh" "shellcheck"
