#!/bin/sh
analyze_shell()
{
    shell_files=$(git ls-files "*.sh")
    if [ -z "$shell_files" ]; then
        return
    fi

    shell_lint=$(git ls-files "*.sh" | xargs shellcheck)
    if [ "$?" -ne "0" ]; then
        echo "Shellcheck linting errors:"
        echo "$shell_lint"
        exit 1
    fi
}

analyze_haskell()
{
    haskell_files=$(git ls-files "*.hs")
    if [ -z "$haskell_files" ]; then
        return
    fi

    haskell_lint=$(git ls-files "*.sh" | xargs shellcheck)
    if [ "$?" -ne "0" ]; then
        echo "HLint errors:"
        echo "$haskell_lint"
        exit 1
    fi
}

analyze_shell
analyze_haskell
